name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: my-server
    steps:
      - uses: actions/checkout@v3

 

      - name: Run a one-line script
        run: echo Hello, world!

 

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
      - name: Create a file
        run: touch /tmp/gagandeep1
      - name: list files
        run: ls
